### DISCUSSION TITLE
Reuse existing volumes

### DISCUSSION THREAD

**Discussion by Hr46ph** [guerzon/vaultwarden#71] [Q&A]
I am running Longhorn for storage provider. I installed Vaultwarden via helm and supplied values.yaml in which I set a domain name and custom size for data and files volumes. Thats it.

Vaultwarden runs fine, and after creating an ingress I can access the gui. I create a user and import a json with some passwords.

I create a backup of the volumes with Longhorn.
I delete vaultwarden via helm uninstall
I delete the current pv's and pvc's
restore pv's from backup.
I create vaultwarden namespace
create pvc vaultwarden-files and vaultwarden-data for the restored volumes.

I reinstall vaultwarden via helm and I kind of expect it to reuse the pvc's as they exist with the same name it would have created them. Instead, it insists on recreating new pv's and pvc's with that name and append the pod name 'vaultwarden-0' to it.

At this point, no matter what I try I cannot get the pod or stateful set to reuse the restored volumes.

I realize I might lack some knowledge on Kubernetes as I am still learning. But after a few hours struggling with this I figured I'd ask because from what I understand it shouldn't be difficult.

I also tried to edit the newly created pvc's to point to the restored pv's. It didnt accept.
I tried to edit the statefulset with kubectl edit, it accepts but it doesnt' change anything. Reopening shows the original values again.

Appreciate some help here!

Thanks!

**Comment by Hr46ph** [comment]
I had also asked the question over at Longhorn discussions:
https://github.com/longhorn/longhorn/discussions/7895

And it seems that the Helm deployment does not take existing pv's into account. Is this correct? I think in that case it would be an important feature to include, the ability to specify existing pv/pvc's.

SInce I posted I also tried backup / restore via Velero which also did not succeed. Upon starting Vaultwarden it seems to recreate new volumes too.

**Comment by Hr46ph** [comment]
Any chance of a reply? Are there any plans on supporting the use of existing PV/PVC's?

**Comment by guerzon** [comment]
Hey @Hr46ph,

- What is the name of the PVC **before** uninstalling Vaultwarden and removing the PV and PVC?
- What is the name of the PVC **after** restoring from Longhorn?
- Could you also provide the relevant lines from your `values.yaml`?

Cheers

**Comment by Hr46ph** [comment]
```
kc get pv,pvc -A | grep vault
persistentvolume/pvc-831e54c1-efa4-4bd6-99bf-b32368c74eee   100Mi      RWO            Delete           Bound    vaultwarden/vaultwarden-data-vaultwarden-0    longhorn       <unset>                          15d
persistentvolume/pvc-fcfe2513-10c0-4266-8310-734b84f79345   1Gi        RWO            Delete           Bound    vaultwarden/vaultwarden-files-vaultwarden-0   longhorn       <unset>                          15d

vaultwarden   persistentvolumeclaim/vaultwarden-data-vaultwarden-0    Bound    pvc-831e54c1-efa4-4bd6-99bf-b32368c74eee   100Mi      RWO            longhorn       <unset>                 15d
vaultwarden   persistentvolumeclaim/vaultwarden-files-vaultwarden-0   Bound    pvc-fcfe2513-10c0-4266-8310-734b84f79345   1Gi        RWO            longhorn       <unset>                 15d
```

The custom values:
```
data:
  name: "vaultwarden-data"
  size: "100Mi"
  # class: ""
  path: "/data"
  keepPvc: true
## @param attachments Attachments directory configuration, refer to values.yaml for parameters.
# By default, attachments/ is located inside the data directory.
#
attachments:
  name: "vaultwarden-files"
  size: "1Gi"
  # class: ""
  path: "/files"
  keepPvc: true
```

As you can see the PV/PVC persist after uninstalling so I don't even have to restore the volumes. If I do restore (which I tested), I have the option in Longhorn to keep the name identical so it will be exactly the same.

When I reinstall vaultwarden with the above settings for the volumes, I get new PV's for which the part that looks like a random UUID string will be different. The PVC's will point to the new volumes instead the existing ones.

**Reply by Hr46ph** [reply]
To add, usually when a helm install supports using existing volumes, it has a setting for it, like this:
```
persistence:
  enabled: true
  type: pvc
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 100Mi
  existingClaim: pvc-example
```
