### DISCUSSION TITLE
Migrate vaultwarden docker compose to kubernetes

### DISCUSSION THREAD

**Discussion by KeyPerformanceGroup** [guerzon/vaultwarden#81] [General]
Hi team, 

I actualy have an up to date vaultwarden installed with docker compose.

I have sevreal users, and a liscence for an organisation. 

Is their any easy solution to migrate this installation to this helm chart version ? 

Thank you for your help.

**Comment by santiagon610** [comment]
> I have sevreal users, and a liscence for an organisation.

I don't believe that Vaultwarden has _any_ licensing mechanism, from anything that I've seen. It just _exists_.

I'm going to assume that since you're using Docker Compose, you're using SQLite as the database backend. In my Kubernetes environment, I'm using Postgres. I followed [this guide from the Vaultwarden app wiki](https://github.com/dani-garcia/vaultwarden/wiki/Using-the-PostgreSQL-Backend#migrating-from-sqlite-to-postgresql) to migrate my database over, used the Helm chart and used my values file to point towards the new database, using a temporary value for `domain` and `ingress.hostname` until I performed a full checkout of the application and ensure that the data appears to be intact.

A redacted version of my `values.yaml` file is below:

```yaml
bump: 0
image:
  pullPolicy: Always
domain: "https://vault.[REDACTED]/"
websocket:
  enabled: true
  address: "0.0.0.0"
  port: 3012
rocket:
  port: 8080
  workers: 10
webVaultEnabled: true
adminToken:
  existingSecret: "awssm-vaultwarden-prod"
  existingSecretKey: "vaultwarden-admin-token"
hibpApiKey: "[REDACTED]"
signupDomains: "[REDACTED]"
signupsVerify: true
showPassHint: true
ingress:
  enabled: true
  class: "nginx"
  tlsSecret: vaultwarden-tls
  hostname: vaultwarden.[REDACTED]
  nginxIngressAnnotations: false
  additionalHostnames:
    - vault.[REDACTED]
  additionalAnnotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
database:
  type: postgresql
  existingSecret: "awssm-vaultwarden-prod"
  existingSecretKey: "VAULTWARDEN_DB_URL_DIRECT"
smtp:
  existingSecret: "awssm-vaultwarden-prod"
  from: "vaultwarden@[REDACTED]"
  host: "smtp.[REDACTED]"
  security: "starttls"
  port: 587
  fromName: "Vaultwarden"
  authMechanism: "Login"
  username:
    existingSecretKey: "smtp-api-username"
  password:
    existingSecretKey: "smtp-api-token"
```

Hope this helps!
