### ISSUE TITLE
Error creating private key - when deploying

### ISSUE THREAD

**Issue by T1gas** [guerzon/vaultwarden#120]
Hi team, got an error here.

When trying to deploy via the following manifest:

```
serviceAccount:
  create: true
  name: "vaultwarden-svc"


securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsGroup: 1001
  runAsUser: 1001
  capabilities:
    drop:
      - ALL

domain: "https://xxxxx.domain.xxx:8443"

resources:
  limits:
    cpu: 300m
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 256Mi

data:
  name: "vaultwarden-data"
  size: "2Gi"
  class: "ceph-filesystem"
  path: "/data"
  keepPvc: false
  accessMode: "ReadWriteOnce"

webVaultEnabled: "true"

ingress:
  enabled: true
  class: "nginx"
  tls: true
  hostname: "vaultwarden-xx.domain.xxx"
  path: "/"
  pathType: "Prefix"
  tlsSecret: "xxxx"

```

gives the following error:

![image](https://github.com/user-attachments/assets/44cfebac-0050-4c99-9141-4d34412fd6d8)

Is this expected? 

Any help would be appreciated!
