### ISSUE TITLE
How to configure SSL with cert-manager

### ISSUE THREAD

**Issue by PedroAugustoRamalhoDuarte** [guerzon/vaultwarden#123]
Thanks for this helm chart it helps a lot

I am trying to setup nginx + cert-manager, is there any support for this feature?

**Comment by santiagon610** [comment]
Yep, it all depends on how your cluster uses cert-manager, but generally it's done with annotations on the ingress.

In my case, it looks something like this:

```yaml
ingress:
  enabled: true
  class: "nginx"
  hostname: "vault.example.com"
  nginxIngressAnnotations: false
  additionalAnnotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # this is the ClusterIssuer that i have cert-manager exposing
    nginx.ingress.kubernetes.io/proxy-body-size: "500m" # this is to allow large uploads for Vaultwarden Send
  tlsSecret: vaultwarden-tls
```

You'll want to use the appropriate ingressClass for your ingress controller, and the appropriate annotation for the `issuer` or `clusterIssuer`.
