### ISSUE TITLE
Nginx Ingress Issue with Admin Page

### ISSUE THREAD

**Issue by waleedzafar68** [guerzon/vaultwarden#126]
I am using the helm chart version of vault-warden. My Problem is that everything works alright except the ingress
If I use the ClusterIP Service that is deployed using Helm and port forward it to my localhost, I can log into the admin portal using token
However using the URL configured on the Ingress the page loads fine, but entering the token says wrong token and there are no logs for  this on the pod logs
Using Nginx Ingress on Tanzu Cluster
Attaching my values.yaml as well 
Using chart 0.29.2
@guerzon 

```
domain: "xxxxxxxxxxxxxxxxxxxxxxx"
database:
  type: postgresql
  existingSecret: "prod-db-creds"
  existingSecretKey: "secret-uri"
pushNotifications:
  enabled: true
  existingSecret: bitwarden-details
  installationId:
    existingSecretKey: "ID"
  installationKey:
    existingSecretKey: "KEY"
smtp:
  existingSecret: "creds"
  host: "xxxxxxxxxxxxxx"
  security: "starttls"
  port: 587
  fromName: "Waleed Zafar"
  from: "xxxxxxxxxxxxxxxxxxx"
  username:
    existingSecretKey: "USERNAME"
  password:
    existingSecretKey: "PASSWORD"
  acceptInvalidCerts: "true"
  debug: true
  
adminToken:
  existingSecret: "token"
  existingSecretKey: "HASH"
ingress:
  enabled: true
  tls: true
  hostname: "xxxxxxxxxxxxxxxxxxxx"
  tlsSecret: "vaultwarden-tls"
  additionalAnnotations:
    nginx.ingress.kubernetes.io/enable-access-log: "true"
    nginx.ingress.kubernetes.io/enable-debug-log: "true"

 ```

**Comment by jsarnowski96** [comment]
Try this out:

```
ingress:
  enabled: true
  class: "nginx"
  hostname: vault.xxx
  nginxIngressAnnotations: false
  additionalAnnotations:
    nginx.ingress.kubernetes.io/connection-proxy-header: "keep-alive"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-connections: "25"
    nginx.ingress.kubernetes.io/limit-rps: "15"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
  tls: false
```

Also make sure that both `domain `and `ingress.hostname` have the same value.
