### ISSUE TITLE
Setting up SEND_EXPIRATION_MAX_DAYS via extraVars/extraSecrets and even directly in ConfigMap has no effect

### ISSUE THREAD

**Issue by jsarnowski96** [guerzon/vaultwarden#129]
I'm trying to enforce a limit on sends expiration time, however regardless of the method used, this particular variable doesn't seem to have any effect.

Example configs I've tested so far:

```
image:
  registry: docker.io
  repository: vaultwarden/server
  tag: "1.32.0"
  pullPolicy: IfNotPresent
  extraVars:
    - key: SEND_EXPIRATION_MAX_DAYS
      value: 3
```

```
image:
  registry: docker.io
  repository: vaultwarden/server
  tag: "1.32.0"
  pullPolicy: IfNotPresent
  extraSecrets:
    - key: SEND_EXPIRATION_MAX_DAYS
      value: "3"
```

I went as far as to directly modyfing VW ConfigMap and adding said variable in it, but just like in two previous cases, setting up the variable didn't have any effect. I also made sure to restart the pod after applying changes in CM.
