### ISSUE TITLE
v0.31.0 removes data volume from deployment

### ISSUE THREAD

**Issue by cterence** [guerzon/vaultwarden#135]
Hi !
Trying to update to this new version removes my existing volume definitions in `.spec.volumes` in the deployment.
My updated values (I just added the new `storage` key, an empty `existingVolumeClaim` key and moved my existing `data` and `attachments` keys in it):

```yaml
storage:
  ## @param existingVolumeClaim If defined, the values here will be used for the data and
  ## attachments PV's. The custom values for data and attachments will be ignored if
  ## a value is set here
  ##
  existingVolumeClaim:
    {}
    # claimName: "vaultwarden-pvc"
    # dataPath: "/data"
    # attachmentsPath: /data/attachments

  ## @param data Data directory configuration, refer to values.yaml for parameters.
  ##
  data:
    name: "vaultwarden-data"
    size: "5Gi"
    class: ""
    path: "/data"
    accessMode: "ReadWriteOnce"
    keepPvc: true

  ## @param attachments Attachments directory configuration, refer to values.yaml for parameters.
  ## By default, attachments/ is located inside the data directory.
  ##
  attachments:
    name: "vaultwarden-files"
    size: "10Gi"
    class: ""
    path: /files
    accessMode: "ReadWriteOnce"
    keepPvc: true
``` 

My diff in ArgoCD (deployment manifest):

![image](https://github.com/user-attachments/assets/76e78797-75a7-4e56-9bfd-d07c8284a07f)

@paimonsoror could you please help since you were the author of this change please ?
