### ISSUE TITLE
0.31.0 Breaks pvc

### ISSUE THREAD

**Issue by samuelJorblad** [guerzon/vaultwarden#138]
I have this in my values file
```
data:
  name: "vaultwarden-data"
  size: "15Gi"
  class: "longhorn"
  path: "/data"
  keepPvc: true
  accessMode: "ReadWriteMany"

attachments:
  name: "vaultwarden-files"
  size: "50Gi"
  class: "longhorn"
  path: /files
  keepPvc: true
  accessMode: "ReadWriteMany"
```
And when I try to upgrade to 0.31.0 or 0.31.1 from 0.30.1 argoCD that I deploy through deletes the PVC and if I try to recreate everything with a newer version I don't get any new PVC:s and because of that I get the error if I really wan't to use volatile storage...
For now I can just use the older version since I cant find what in your changes that breaks it in my environment.
