### ISSUE TITLE
OIDCwarden avabilitty 

### ISSUE THREAD

**Issue by delta-whiplash** [guerzon/vaultwarden#143]
Hello could it be possible to pick in the config another image for the docker container 
Like : https://github.com/Timshel/OIDCWarden
It could be really interesting to have this features

**Comment by guerzon** [comment]
Hi @delta-whiplash, yes you can. Something like:

```yaml
image:
  registry: ghcr.io
  repository: timshel/oidcwarden
  tag: "latest"
```

https://github.com/guerzon/vaultwarden/tree/main/charts/vaultwarden#general-configuration
