### ISSUE TITLE
Chart does not seem to use database config

### ISSUE THREAD

**Issue by seraphblade2010** [guerzon/vaultwarden#146]
I tried to install the helmchart today and use my own postgresql database but it always resorts to sqlite.
Can you point me in the right direction? helm chart values are below:
```
  values:
# # Below this start the customized values of the helmchart
    image:
      repository: 'vaultwarden/server'
      tag: 1.33.0
      registry: docker.io
      
    domain: {redacted}
    signupsAllowed: true
    
    adminToken:
      value: {redacted}
    
    timeZone: "Europe/Berlin"

    ingress:
      enabled: true
      class: "traefik"
      nginxIngressAnnotations: false
      additionalAnnotations:
        cert-manager.io/cluster-issuer: "cluster-issuer-letsencrypt-ionos-prod"
      hostname: {redacted}
      path: "/"
      pathType: Prefix
      tls: true
      tlsSecret: certificate-vaultwarden-tls

    storage:
      data:
        name: "vaultwarden-data"
        size: "5Gi"
        path: "/data"
        class: "proxmox-data-infrastructure"
        keepPvc: true
        accessMode: "ReadWriteOnce"
      attachments:
        name: "vaultwarden-files"
        size: "5Gi"
        path: "/files"
        class: "proxmox-data-infrastructure"
        keepPvc: true
        accessMode: "ReadWriteOnce"

    database:
      type: postgresql
      host: postgresql
      port: 5432
      dbName: vault
      username: vaultwarden
      existingSecret: sealed-secret-vaultwarden-passwords
      existingSecretKey: vaultwarden-postgresql-password
```
