### ISSUE TITLE
When launching helm install with the basic configuration, it does not start

### ISSUE THREAD

**Issue by Dazag** [guerzon/vaultwarden#157]
I have followed the documentation in this repository without much success.
I am using factory k3s, I have just installed (k3s) it and it works fine with another deployment I made.

### Helm command:
```
export NAMESPACE=vaultwarden
export DOMAIN_NAME=pass.company.com

helm install vaultwarden-release vaultwarden/vaultwarden \
  --namespace $NAMESPACE \
  --set "ingress.enabled=true" \
  --set "ingress.hostname=$DOMAIN_NAME"
```

### Shown in console after launching it: 
```
NAME: vaultwarden-release
LAST DEPLOYED: Thu Mar 20 06:18:21 2025
NAMESPACE: vaultwarden
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **

Thanks for installing vaultwarden.

You have named your release: vaultwarden-release.

Vaultwarden is accessible here: vaultwarden.mydomain.com
```

### Result: 
Pod forever restarting: 
Back-off restarting failed container vaultwarden in pod vaultwarden-release-0_vaultwarden(23587894-4bb0-4d0a-a4c7-56b85b82cf61)

This is what I see when I check the logs.

### Logs: (`kubectl logs -n vaultwarden vaultwarden-release-0`)
/--------------------------------------------------------------------\
|                        Starting Vaultwarden                        |
|                           Version 1.33.2                           |
|--------------------------------------------------------------------|
| This is an *unofficial* Bitwarden implementation, DO NOT use the   |
| official channels to report bugs/features, regardless of client.   |
| Send usage/configuration questions or feature requests to:         |
|   https://github.com/dani-garcia/vaultwarden/discussions or        |
|   https://vaultwarden.discourse.group/                             |
| Report suspected bugs/issues in the software itself at:            |
|   https://github.com/dani-garcia/vaultwarden/issues/new            |
\--------------------------------------------------------------------/

Error validating domain: relative URL without a base
Error loading config:
  DOMAIN variable needs to contain the protocol (http, https). Use 'http[s]://bw.example.com' instead of 'bw.example.com'

### This is what happens when I add https:// to the domain name and launch the previous command again:

"Ingress.networking.k8s.io "vaultwarden-release" is invalid: [spec.rules[0].host: Invalid value: "https://vaultwarden.mydomain.com/": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9 ([-a-z0-9]*[a-z0-9])?(.a-z0-9 ([-a-z0-9]*[a-z0-9])?)'), spec.tls[0].hosts[0]: Invalid value: "https://vaultwarden.mydomain.com/": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9 ([-a-z0-9]*[a-z0-9])?(.a-z0-9 ([-a-z0-9]*[a-z0-9])?)')]"

**Comment by santiagon610** [comment]
This makes sense. The Helm chart is templating the ingress, which only wants the FQDN to be attached thereto.

As I understand it, the `Values.domain` is used to generate the URLs inside the web UI, but the `Values.ingress.hostname` is what's used to generate the ingress and TLS secret.

This is how I have my values set up in order to have a TLS-fronted ingress:
```yaml
        domain: "https://vault.redacted.com/"
        rocket:
          port: 8080
          workers: 10
        webVaultEnabled: true
        adminToken:
          existingSecret: "vaultwarden-secret"
          existingSecretKey: "VAULTWARDEN_ADMIN_TOKEN"
        ingress:
          enabled: true
          class: "nginx"
          tlsSecret: vaultwarden-tls
          hostname: vault.redacted.com
          nginxIngressAnnotations: false
          additionalHostnames: []
```

Hope this helps!

**Comment by spectroman** [comment]
Im stumbling in a similar issue, using K8s , doing a deployment via helm, gitops, argoCD.

I do not want to set an Ingres, I will set things up in a different way while I test. As such I understand I should have the option to:

```
        ingress:
          enabled: false
```

So, I am giving him the `DOMAIN` variable as requested, but he seems to ignore the value in there.

Even though ingress is disabled, and I provide a `ingress.hostname`, it also doesn't make any difference.

Not sure what might be the problem.

**Comment by spectroman** [comment]
So reading with more attention I figured that I need to add `domain` in the values, it looks like:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vaultwarden
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://guerzon.github.io/vaultwarden
    chart: vaultwarden
    targetRevision: 0.31.8 # or latest
    helm:
      values: |
        image:
          repository: vaultwarden/server
          tag: "latest"

        service:
          type: LoadBalancer
          port: 80
          annotations: {}

        ingress:
          enabled: false

        env:
          SIGNUPS_ALLOWED: "false"
          ADMIN_TOKEN: "07wutwutwutwut5c"

        domain: "http://vaultw.bingbong.com"
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 1Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```

like that, it worked fine.
