### ISSUE TITLE
High available vaultwarden possible?

### ISSUE THREAD

**Issue by Tockra** [guerzon/vaultwarden#158]
Hey,

the readme here in the repo says you can set:
```
replicas: 10

service:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
```

But I wanted to ask how this should work? I know I can connect a postgresql database. But some parts of vaultwarden are stored on the storage and I think some key files.
So how could a cluster with ReadWriteOnce (or no) volumes  work?

T
