### ISSUE TITLE
Some vars can't be set to allow  Non-SSL auth mehanism for SMTP

### ISSUE THREAD

**Issue by ShootGan** [guerzon/vaultwarden#18]
According to this https://github.com/dani-garcia/vaultwarden/discussions/3477 I think it should be possibility to left this variables empty. 
### Possible solution: 
in the configmap add:
```yaml
  {{- if .Values.smtp.authMechanism }}
  SMTP_AUTH_MECHANISM: {{ .Values.smtp.authMechanism | quote }}
  {{- end }}
```
in the statefulset add:
```yaml
 {{- if .Values.smtp.username }}
            - name: SMTP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaultwarden.fullname" . }}
                  key: SMTP_USERNAME
            {{- end }}
            {{- if .Values.smtp.password }}
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "vaultwarden.fullname" . }}
                  key: SMTP_PASSWORD
            {{- end }}
```

I can prepare a pull request with these changes.
