### ISSUE TITLE
Websocket notification path/ingress 

### ISSUE THREAD

**Issue by skysbsb** [guerzon/vaultwarden#21]
Hey, i noticed that you are using `ImplementationSpecific` as default pathTypeWs at WS ingress part.
As shown here:
```
  path: "/"
  ## @param ingress.pathWs Path for the websocket ingress
  ##
  pathWs: "/notifications/hub"
  ## @param ingress.pathType Path type for the ingress
  ## Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ##
  pathType: "ImplementationSpecific"
  ## @param ingress.pathTypeWs Path type for the ingress
  ## Ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ##
  pathTypeWs: "ImplementationSpecific"
```

And this is how you set the ingress template:
```
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
        - path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType }}
          backend:
            service:
              name: {{ include "vaultwarden.fullname" . }}
              port:
                name: "http"
        {{- if .Values.websocket.enabled }}
        - path: {{ .Values.ingress.pathWs }}
          pathType: {{ .Values.ingress.pathTypeWs }}
          backend:
            service:
              name: {{ include "vaultwarden.fullname" . }}
              port:
                name: "websocket"
        {{- end }}
```
But according to the [official documentation](https://github.com/dani-garcia/vaultwarden/wiki/Enabling-WebSocket-notifications#:~:text=To%20enable%20WebSockets,port%2080.):

> To enable WebSockets notifications, an external reverse proxy is necessary, and it must be configured to do the following:
> Route the /notifications/hub endpoint to the WebSocket server, by default at port 3012, making sure to pass the Connection and Upgrade headers. (Note the port can be changed with WEBSOCKET_PORT variable)
> Route everything else, including /notifications/hub/negotiate, to the standard Rocket server, by default at port 80.

So, if i understand correctly, only `/notifications/hub` should reach to WS port. Thus, pathTypeWs should be `Exact` instead of `ImplementationSpecific` for [nginx-ingress-controller](https://docs.nginx.com/nginx-ingress-controller/configuration/ingress-resources/basic-configuration/#:~:text=ImplementationSpecific%2C%20which%20is%20the%20default%20type%20and%20is%20the%20same%20as%20Prefix.), right?
