### ISSUE TITLE
Add imagePullSecret support

### ISSUE THREAD

**Issue by eirisdg** [guerzon/vaultwarden#85]
In order to deploy images from private registries, support for imagePullSecrets is needed in the deployment.

**Comment by guerzon** [comment]
Please excuse the delay @eirisdg. You can now use `imagePullSecrets`, sample values below.

```yaml
image:
  registry: ghcr.io
  repository: guerzon/vaultwarden
  pullSecrets:
    - name: regcred
```
