### ISSUE TITLE
Improve database existingSecret functionality

### ISSUE THREAD

**Issue by davidfrickert** [guerzon/vaultwarden#92]
The current existingSecret options is not great. It forces you to create a secret with the full database URI including host and credentials.
I think the chart should support passing each param separately. 
Ideal format (taken from bitnami/keycloak)

```
externalDatabase:
  host: tools-pg
  user: bn_keycloak
  database: bitnami_keycloak
  existingSecret: bn-keycloak.tools-pg.credentials.postgresql.acid.zalan.do
  existingSecretUserKey: username
  existingSecretPasswordKey: password
```

The big benefit is that i can re-use the generated secret from posgres operator very easily and in current setup i have to create a new secret with full DB url which is not great. It also does not allow me to take advantage of automatic credential rotation.

current setup:
```
database:
  type: postgresql
  existingSecret: vaultwarden-pg
  existingSecretKey: uri
```

proposed setupp:

```
database:
  type: postgresql
  existingSecret: vaultwarden-pg
  host: tools-pg
  user: bn_keycloak
  database: bitnami_keycloak
  existingSecret: bn-keycloak.tools-pg.credentials.postgresql.acid.zalan.do
  existingSecretUserKey: username
  existingSecretPasswordKey: password
  # existingSecretKey: uri
```

If `existingSecretKey` is set then use it, else use individual settings.
